data_dir: '/Users/sneha/Downloads/CBMs'
train_dir: '/Users/sneha/Downloads/CBMs/train.pkl'
test_dir: '/Users/sneha/Downloads/CBMs/test.pkl'
val_dir: '/Users/sneha/Downloads/CBMs/val.pkl'
# train_csv: 'train_gt.csv'
# test_csv: 'test_gt.csv'
output_dir: /Users/sneha/Downloads/CBMs/logs
output_file: best_model_1.pth

train_params:
  num_workers: 1
  resize: 224
  num_epochs: 10
  batch_size: 32
  patience: 3
  early_stopping: False

optimizer:
  learning_rate: 0.0001

input_size: 224
num_classes: 2 # Benign and Malignant
freeze_features: False # Set True to freeze feature extractor